name: previewPR

on:
  pull_request   
  
jobs:
  previewPR:
    runs-on: ubuntu-latest
    steps:
    
    
      - name: Clone
        uses: actions/checkout@v1
        with:
          repository: devonfw/devonfw.github.io
          ref: develop
          submodules: recursive
      #website repo

      #delete architectures
      - name: Delete old architectures
        run: |
          cd ../../
          cd architectures/devonfw.github.io
          rm -r architectures
          
      #clone architectures repo (path = architectures)
      - name: Add new architectures
        uses: actions/checkout@v1
        with:
          path: architectures/devonfw.github.io
          
      - name: Move new architecure to right place
        run: |
          cd ../../
          cd devonfw.github.io
          mkdir architectures 
          cd ../
          cp -a architectures/devonfw.github.io/. devonfw.github.io/architectures
          ls
          pwd
          ls devonfw.github.io/architectures
          #rm -r architectures
          
      - name: Edit pom.xml File 
        run: |
          cd ../../
          cd devonfw.github.io
          
          sudo apt-get install xmlstarlet
          
          
          #xmlstarlet edit --update "project/modules/module/@website" --value "" pom.xml 
          xmlstarlet ed -d "//project/modules[last()]" pom.xml 
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          xmlstarlet ed -u "project/modules" -v "test" pom.xml 
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          xmlstarlet sel -t -c "/" pom.xml 
          
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          
          #xmlstarlet sel -t -c "/" pom.xml 
          #xmlstarlet edit --update "project/modules/module/@search-engine" --value "" pom.xml 
          
          #echo "---------------------------------------------------------------------------------"
          #pwd
          #echo "---------------------------------------------------------------------------------"
          
          #xmlstarlet sel -t -c "/" pom.xml 

          
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Solutions from Stack repositories
        run: |
          cd ../../
          cd devonfw.github.io
          cd architectures/scripts
          
          npm install
          node copySolutionsFromStack.js ../../devonfw-guide
          cd ../../

      - name: Copy pom files for architectures
        run: |
          chmod +x scripts/copyPomFiles.sh
          scripts/copyPomFiles.sh

      - name: npm install for architectures
        run: |
          cd scripts
          npm install
          cd ../../
          
      # asciidoctor tries to load gems dynamically to convert md and scss files.
      # As this gems are not installed this is breaking the build.
      - name: Remove files that are breaking the build
        run: |
          pwd
          ls
          rm README.md || true
          rm index.scss || true

      - name: Compile sass for architectures
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: index.scss
          destination: index.css

      - name: Build
        run: |
          cd ../../
          pwd 
          ls devonfw.github.io
          cd devonfw.github.io
          ls
          xmlstarlet sel -t -c "/" pom.xml 
          mvn -s ./.m2/unblock-rubygem-proxy-settings.xml clean package
          pwd 
          ls
          xmlstarlet sel -t -c "/" pom.xml 

      - name: Create output for architectures
        run: |
          pwd
          ls
          cd ../
          pwd 
          ls
          cd ../
          pwd 
          ls
          cd devonfw.github.io
          pwd
          ls
          chmod +x architectures/scripts/createOutput.sh
          architectures/scripts/createOutput.sh
          pwd
          ls

      - name: Copy output of architectures
        run: |
          cd ../../
          pwd
          ls
          pwd
          ls devonfw.github.io
          cd devonfw.github.io
          pwd
          ls architectures
          cp -avr architectures/target/generated-docs/ target/generated-docs/website/pages/architectures/
    
    
    
    #############
    
    
    
      - name: Clone new architecture
        uses: actions/checkout@v1
        #with:
          #ref: ${{ github.event.pull_request.head.sha }}
          
          
      - name: Run maven generate
        run: |
              mkdir PR_preview
              cp -r solutions PR_preview
              cp -a PRfiles/. PR_preview
              cd PR_preview
              mvn clean package
              
      - name: Run image generate
        run: |
              cd PR_preview
              npm install node-html-to-image-cli -g
              cd target/generated-docs
              node-html-to-image-cli index.html image.png              
        
        
      - name: Artifact build
        uses: actions/upload-artifact@v2
        with: 
          name: download-asset
          path: |
                PR_preview/target/generated-docs/image.png
                PR_preview/target/generated-docs/index.html
