name: previewPR

on:
  pull_request   
  
jobs:
  previewPR:
    runs-on: ubuntu-latest
    steps:      
    ##############
    
      #- name: Clone new architecture
       # uses: actions/checkout@v1
        #with:
          #ref: ${{ github.event.pull_request.head.sha }}
          
          
     # - name: Run maven generate
      #  run: |
       #       mkdir PR_preview
        #      cp -r solutions PR_preview
         #     cp -a PRfiles/. PR_preview
          #    cd PR_preview
           #   mvn clean package
              
      #- name: Run image generate
        #run: |
            #  cd PR_preview
            #  npm install node-html-to-image-cli -g
            #  cd target/generated-docs
            #  node-html-to-image-cli index.html image.png              
        
        
      #- name: Artifact build
      #  uses: actions/upload-artifact@v2
      #  with: 
       #   name: download-asset
       #   path: |
              #  PR_preview/target/generated-docs/image.png
              #  PR_preview/target/generated-docs/index.html
                
  ###################
      
      - name: Checkout playbooks
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorials
          path: playbooks
      - id: changedfiles
        uses: jitterbit/get-changed-files@v1
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          dirs=()
          for changed_file in ${{ steps.changedfiles.outputs.all }}; do
          
            dir="$(echo ${changed_file} | cut -d/ -f2)"           
            check="$(echo $changed_file | cut -d/ -f1)"
           
            if [[ ! " ${dirs[@]} " =~ " ${dir} " ]];  then
              if [["t" == "solutions"]]; then
                MATRIX_PARAMS_COMBINATIONS=$MATRIX_PARAMS_COMBINATIONS'{"solution": "'$dir'"},'
                dirs+=($dir)
                echo $dir
                echo ------
                echo $MATRIX_PARAMS_COMBINATIONS
                echo ------
                #echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
              fi
           fi
           # && ["$check" == "solutions"];
          # dirs+=($dir)
          done
          echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}
      
  build_pullRequest:
    runs-on: ubuntu-latest
    needs: previewPR
    strategy:
      matrix: ${{ fromJson(needs.previewPR.outputs.matrix-combinations) }}
    steps:
      - name: Clone
        uses: actions/checkout@v1
        with:
          repository: devonfw/devonfw.github.io
          ref: develop
          submodules: recursive
      #website repo

      #delete architectures
      - name: Delete old architectures
        run: |
          echo $matrix
          cd ../../
          cd architectures/devonfw.github.io
          rm -r architectures
          
      #clone architectures repo (path = architectures)
      - name: Add new architectures
        uses: actions/checkout@v1
        with:
          path: architectures/devonfw.github.io
          
      - name: Move new architecure to right place
        run: |
          cd ../../
          cd devonfw.github.io
          mkdir architectures 
          cd ../
          cp -a architectures/devonfw.github.io/. devonfw.github.io/architectures
          #rm -r architectures
          
      - name: Edit pom.xml File 
        run: |
          cd ../../
          cd devonfw.github.io
          
          sudo apt-get install xmlstarlet
          
          pwd
          ls
          
          #xmlstarlet edit --update "project/modules/module/@website" --value "" pom.xml 
          #xmlstarlet ed -d "//project/modules[last()]" pom.xml 
          #xmlstarlet ed -d "//project[last()]" pom.xml 
          #xmlstarlet ed -r "/project/modules" -v "TESTEN" pom.xml  
          #xmlstarlet ed -d "xml/project/modules/module" pom.xml
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          #xmlstarlet ed -u "project/modules/@module" -v 5 pom.xml 
          #xml ed -d "/project/modules" pom.xml
          #xmlstarlet ed -d "/project/modules/module" pom.xml
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          #xmlstarlet sel -t -c "/" pom.xml 
          #xml ed -d "/project/modules" pom/project/module.xml
          
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          
          #xmlstarlet sel -t -c "/" pom.xml 
          #xmlstarlet edit --update "project/modules/module/@search-engine" --value "" pom.xml 
          
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          
          #xmlstarlet sel -t -c "/" pom.xml 
          xmlstarlet ed --inplace -u '/project/modules/module/' -x 'string("architectures")' pom.xml

          
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Solutions from Stack repositories
        run: |
          cd ../../
          cd devonfw.github.io
          cd architectures/scripts
          
          npm install
          node copySolutionsFromStack.js ../../devonfw-guide
          cd ../../

      - name: Copy pom files for architectures
        run: |
          chmod +x scripts/copyPomFiles.sh
          scripts/copyPomFiles.sh

      - name: npm install for architectures
        run: |
          cd scripts
          npm install
          cd ../../
          
      - name: Compile sass for architectures
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: index.scss
          destination: index.css
          
      # asciidoctor tries to load gems dynamically to convert md and scss files.
      # As this gems are not installed this is breaking the build.
      - name: Remove files that are breaking the build
        run: |
          pwd
          ls
          rm README.md || true
          rm index.scss || true

      - name: Build
        run: |
          cd ../../
          cd devonfw.github.io
          #xmlstarlet sel -t -c "/" pom.xml 
          mvn -s ./.m2/unblock-rubygem-proxy-settings.xml clean package

          #xmlstarlet sel -t -c "/" pom.xml 

      - name: Create output for architectures
        run: |
          cd ../../
          cd devonfw.github.io
          pwd
          ls
          pwd
          ls architectures
          pwd
          ls architectures/solutions

          chmod +x architectures/scripts/createOutput.sh
          architectures/scripts/createOutput.sh

      - name: Copy output of architectures
        run: |
          cd ../../
          echo ${matrix}
          pwd
          #echo ${matrix.solution}
          cd devonfw.github.io

          cp -avr architectures/target/generated-docs/ target/generated-docs/website/pages/architectures/
          
      - name: Run image generate
        run: |
              cd ../../
              cd devonfw.github.io
              npm install node-html-to-image-cli -g
              cd architectures/target/generated-docs
              node-html-to-image-cli index.html image.png 
        
      - name: Artifact build
        uses: actions/upload-artifact@v2
        with: 
          name: download-asset
          path: |
                /home/runner/work/architectures/devonfw.github.io/architectures/target/generated-docs/image.png
                /home/runner/work/architectures/devonfw.github.io/architectures/target/generated-docs/index.html
          

      #- name: run buildRun.sh
       # run: sh buildRun.sh --user ${{ github.actor }} --branch ${{ github.event.pull_request.head.ref }} -p ${{ matrix.solution }}
       
      - name: run buildRun.sh
        run: |
            touch buildRun.sh
            sh buildRun.sh ${{ matrix.solution }}
            echo $buildRun.sh
            echo buildRun.sh
            sh buildRun.sh
            echo $buildRun
            echo $matrix
            echo $matrix.tutorial
            echo ${{ matrix.solution }}
            echo matrix.solution
            echo $matrix.solution
            
            pwd
            ls
            cd ../../
            cd devonfw.github.io
            pwd
            ls architectures
            pwd
            ls target
            pwd
            ls target/generated-docs
            pwd
            ls architectures/target/generated-docs
            pwd
            ls architectures/target
            pwd 
            ls architectures/solutions
            pwd
            sh -x buildRun.sh
            pwd
            sh -x buildRun
    
    outputs:
        comment-combinations: --user ${{ github.actor }} --branch ${{ github.event.pull_request.head.ref }} -p ${{ matrix.solution }}
        
  comment:
    runs-on: ubuntu-latest
    needs: build_pullRequest
    strategy:
      matrix: ${{ fromJson(needs.build_pullRequest.outputs.comment-combinations) }}
    steps:
    
      - name: Test Run
        run: |
          echo ${matrix}
    
     #- name: Run image generate
        #run: |
            #  cd PR_preview
            #  npm install node-html-to-image-cli -g
            #  cd target/generated-docs
            #  node-html-to-image-cli index.html image.png              
        
        
      #- name: Artifact build
      #  uses: actions/upload-artifact@v2
      #  with: 
       #   name: download-asset
       #   path: |
              #  PR_preview/target/generated-docs/image.png
              #  PR_preview/target/generated-docs/index.html
