name: previewPR

on:
  pull_request   
  
jobs:
  previewPR:
    runs-on: ubuntu-latest
    steps:
    
    
      - name: Clone
        uses: actions/checkout@v1
        with:
          repository: devonfw/devonfw.github.io
          ref: develop
          submodules: recursive
      #website repo

      #delete architectures
      #clone architectures repo (path = architectures)


      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Solutions from Stack repositories
        run: |
          cd ../../
          ls
          pwd
          ls architectures
          pwd
          ls architectures/architectures
          pwd
          ls architectures/devonfw.github.io
          cd architectures/scripts
          npm install
          node copySolutionsFromStack.js ../../devonfw-guide
          cd ../../

      - name: Copy pom files for architectures
        run: |
          chmod +x architectures/scripts/copyPomFiles.sh
          architectures/scripts/copyPomFiles.sh

      - name: npm install for architectures
        run: |
          cd architectures/scripts
          npm install
          cd ../../

      - name: Compile sass for architectures
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: architectures/index.scss
          destination: architectures/index.css



      # asciidoctor tries to load gems dynamically to convert md and scss files.
      # As this gems are not installed this is breaking the build.
      - name: Remove files that are breaking the build
        run: |
          rm architectures/README.md || true
          rm architectures/index.scss || true

      - name: Build
        run: mvn -s ./.m2/unblock-rubygem-proxy-settings.xml clean package

      - name: Create output for architectures
        run: |
          chmod +x architectures/scripts/createOutput.sh
          architectures/scripts/createOutput.sh

      - name: Copy output of architectures
        run: |
         cp -avr architectures/target/generated-docs/ target/generated-docs/website/pages/architectures/
    
    
    
    
    
      - name: Clone new architecture
        uses: actions/checkout@v1
        #with:
          #ref: ${{ github.event.pull_request.head.sha }}
          
          
      - name: Run maven generate
        run: |
              mkdir PR_preview
              cp -r solutions PR_preview
              cp -a PRfiles/. PR_preview
              cd PR_preview
              mvn clean package
              
      - name: Run image generate
        run: |
              cd PR_preview
              npm install node-html-to-image-cli -g
              cd target/generated-docs
              node-html-to-image-cli index.html image.png              
        
        
      - name: Artifact build
        uses: actions/upload-artifact@v2
        with: 
          name: download-asset
          path: |
                PR_preview/target/generated-docs/image.png
                PR_preview/target/generated-docs/index.html
