name: previewPR

on:
  pull_request_target    
  
jobs:
  previewPR:
    runs-on: ubuntu-latest
    steps:
    
    
      - name: Clone new architecture
        uses: actions/checkout@v1
        with:
          destination: devonfw.github.io/
          submodules: recursive
          
          
      - name: Run maven generate
        run: |
              cd testFolder
              ls
              #chmod +x pom.xml
              mvn clean package
              ls


      #- uses: actions/checkout@v2
      - name: Run image generate
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
        run: |
              cd testFolder
              npm install
              pwd 
              ls target
              cd target/generated-docs
              node-html-to-image-cli index.html image.png 
      
      
     
      - name: artifacts1
        run: 
            mkdir testerFolder
        
      - name: artifacts2
        run: |
             cd testerFolder
             echo 'testEcho' > testFile.html
             cd ..
        
      - name: artifacts3
        uses: actions/upload-artifact@v2
        with: 
          name: download-asset
          path: testerFolder
      
      
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{runner.os }}-maven-
      - name: Setup Node
        uses: actions/setup-node@v2


      - name: Solutions from Stack repositories
        run: |
          #cd architectures/scripts
          cd scripts
          npm install 
          node copySolutionsFromStack.js ../../devonfw-guide
          cd ../../
          
      - name: Copy pom files for architectures
        run: |
          chmod +x architectures/scripts/copyPomFiles.sh
          architectures/scripts/copyPomFiles.sh
          
      - name: npm install for architectures
        run: |
          cd architectures/scripts
          npm install
          cd ../../
          
      - name: Compile sass for architectures
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: architectures/index.scss
          destination: architectures/index.css


      # asciidoctor tries to load gems dynamically to convert md and scss files.
      # As this gems are not installed this is breaking the build.
      - name: Remove files that are breaking the build
        run: |
          rm architectures/README.md || true
          rm architectures/index.scss || true
          
      - name: Build
        run: mvn -s ./.m2/unblock-rubygem-proxy-settings.xml clean package
